### ISSUE TITLE
code for the miniimagenet

### ISSUE THREAD

**Issue by zheshiyige** [jaesik817/bmaml#1]
Hello,

       Could you also provide the code of Mini-imagenet? Thank you!

**Comment by jsikyoon** [comment]
Hi,

For classification task, we didn't clean the code and decision to open is
in progress.

Thank you for your interesting.

BRs, Jaesik.

2019년 9월 21일 (토) 오전 6:45, zheshiyige <notifications@github.com>님이 작성:
